use_frameworks!

platform :ios, '8.0'

target 'LPNetworking_Example' do
  pod 'LPNetworking', :path => '../'

  target 'LPNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
